name: Deploy to Contabo

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy over SSH using key
        uses: appleboy/ssh-action@v1
        with:
          host: "66.94.116.153"
          username: "semillero"
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: 22
          script: |
            cd ~/apps/semillero-discord-bot
            git pull
            docker compose down || true
            docker compose up -d --build
